{{ config(alias='curriculo_periodo', schema='educacao_basica_frequencia') }}

SELECT
    SAFE_CAST(crp_id AS STRING) AS id_periodo_curriculo,
    SAFE_CAST(crp_ordem AS INT64) AS ordem_periodo,
    SAFE_CAST(crp_descricao AS STRING) AS descricao_periodo,
    SAFE_CAST(crp_idadeIdealAnoInicio AS INT64) AS ano_idade_inicio,
    SAFE_CAST(crp_idadeIdealMesInicio AS INT64) AS mes_idade_inicio,
    SAFE_CAST(crp_idadeIdealAnoFim AS INT64) AS ano_idade_final,
    SAFE_CAST(crp_idadeIdealMesFim AS INT64) AS mes_idade_final,
    SAFE_CAST(crp_situacao AS INT64) AS situacao,
    SAFE_CAST(crp_dataCriacao AS DATETIME) AS data_criacao,
    SAFE_CAST(crp_dataAlteracao AS DATETIME) AS data_alteracao,
    SAFE_CAST(crp_controleTempo AS INT64) AS controle_tempo,
    SAFE_CAST(crp_qtdeDiasSemana AS INT64) AS aulas_semana,
    SAFE_CAST(crp_qtdeTemposSemana AS INT64) AS tempos_semana,
    SAFE_CAST(crp_qtdeHorasDia AS INT64) AS horas_dia,
    SAFE_CAST(crp_qtdeMinutosDia AS INT64) AS minutos_dia,
    SAFE_CAST(crp_qtdeEletivasAlunos AS INT64) AS eletivas,
    SAFE_CAST(crp_ciclo AS STRING) AS ciclo,
    SAFE_CAST(crp_turmaAvaliacao AS BOOL) AS turma_avalicao,
    SAFE_CAST(crp_nomeAvaliacao AS STRING) AS nome_avaliacao,
    SAFE_CAST(crp_qtdeTemposDia AS INT64) AS qtd_tempos_dia,
    SAFE_CAST(crp_concluiNivelEnsino AS BOOL) AS crp_concluiNivelEnsino,
    SAFE_CAST(crp_fundoFrente AS STRING) AS crp_fundoFrente,
    SAFE_CAST(clg_id AS STRING) AS clg_id,
    SAFE_CAST(tcp_id AS STRING) AS numero_coc,
    SAFE_CAST(crr_id AS STRING) AS id_curriculo,
    SAFE_CAST(mep_id AS STRING) AS id_etapa_mec_inep,
    SAFE_CAST(tci_id AS STRING) AS tci_id,
    SAFE_CAST(cur_id AS STRING) AS id_curso
FROM `rj-sme.educacao_basica_frequencia_staging.curriculo_periodo`